### ISSUE TITLE
Disc numbers in addition to track numbers

### ISSUE THREAD

**Issue by NoStereo** [sll552/DiscordBee#127]
**Is your feature request related to a problem? Please describe.**

This may be a bug; I wasn't sure if this is intended behavior or not but if I change the track total to also include "/[DiscNo]" it fails to appear. I've tried a few things but anything other than a placeholder will cause the track numbers to not show at all. [TrackCount][DiscNo] works but is obviously undesirable.

This however probably falls more under a feature request if this could be a "smart" feature, ignoring null values and falling back to operate as it does now for single CD releases.

**Describe the solution you'd like**
I'd like to be able to display (3 of 9 - Disc 2) or at least (3 of 9/2) on multi–CD Albums.

**Comment by sll552** [comment]
The problem is that these two fields are numbers only (which is not really reflected in the ui) so unfortunately it wont be possible to add anything there that is not a number see https://discord.com/developers/docs/rich-presence/how-to#updating-presence-update-presence-payload-fields (partySize, partyMax) for more info.

Unfortunately there is nothing I can do about that so if you want something like this maybe try using another field for that.
