### ISSUE TITLE
Old boring icon

### ISSUE THREAD

**Issue by raemun** [sll552/DiscordBee#20]
Is there a way for users to change the icon? If not, it'd be better if we changed the icon to something modern like this one.
![flyBee_shaded](https://user-images.githubusercontent.com/52664823/60814700-c8f64c00-a19e-11e9-901a-473e37512a69.png)

**Comment by sll552** [comment]
Users can not change the icon as it is configured through discords developer portal (as all images are). 

I am using the official musicbee icon, as it is used on the website. This is not going to change especially because using something else could cause legal issues or at least needs explicit permission from the creator.

Maybe I will get rid of the yellow background in the future but the icon won't change.

**Comment by wopian** [comment]
I think it would be better to match the MusicBee logo exactly by getting rid of the yellow background. Transparent images for the application logo look pretty decent in the Rich Presence layout.

![image](https://user-images.githubusercontent.com/3440094/83559697-eea1e780-a50c-11ea-8bec-edf6fe8e4ddd.png)

**Comment by sll552** [comment]
Does anybody have a high quality (official) source for the image? I guess i could try the .ico file inside the install folder but this naturally has a bad resolution so I don't think it will look good. Nonetheless I will change it late today and see how it works out.

You will notice the change immediately so please give feedback as soon as possible.

**Comment by wopian** [comment]
515×447

![MusicBee_Logo](https://user-images.githubusercontent.com/3440094/84685877-e39a7e80-af32-11ea-99c5-0e757a88d4f4.png)

**Comment by sll552** [comment]
Thanks I changed it, due to caching it might take a few minutes to be visible. May I ask where you found this one?

**Comment by wopian** [comment]
>May I ask where you found this one?

The original artist posted the original images (well … PowerPoint) on the MusicBee forums in 2011 https://getmusicbee.com/forum/index.php?topic=2494.msg16551#msg16551

The Dropbox link is long since dead, but the Russian Wikimedia project saved it in 2012 https://ru.wikipedia.org/wiki/Файл:MusicBee_Logo.png

**Comment by sll552** [comment]
Ok, wow thats some serious archaeology you did there 👍

**Comment by sll552** [comment]
As it should be live for a little while now, how does everyone like it?

**Comment by raemun** [comment]
I like this icon much more. thank you very much.

**Comment by sll552** [comment]
As no one seems to dislike it, I am closing this and the new icon will stay for now.
