### ISSUE TITLE
Allow us to change the "of" between the two fields in the parentheses

### ISSUE THREAD

**Issue by Rings4** [sll552/DiscordBee#30]
https://i.imgur.com/sHFqKES.png
I'd like to be able to edit the word in between the two fields in the parentheses. Right now it's [TrackNo] of [Year]. I chose [Year] as the second field because none of my tracks have the total tracks tag, so it would always show 1 of 1. Perhaps the new version 1.3.1 fixed that, but as it stands, the second field would still be unused in my case.
Allowing the user to choose which word is shown between the two fields would open up the possibilities of tag combinations. I could for example say "[TrackNo] from [Year]".

**Comment by sll552** [comment]
I agree with you that this would be a nice feature but unfortunately the "x of x" is not something I can change as this is hardcoded at Discords API. The plugin and therefore you as a user can only change the two numbers and even for that there are some rules (e.g. the 2nd number must be higher than the first one).

This is because the whole feature of these custom Discord status messages was developed around games and their state. The feature in question is intended for showing party/squad size and I am just abusing this. All fields that can be set are documented [here](https://discordapp.com/developers/docs/rich-presence/how-to#updating-presence) if you are interested in knowing the background to this, there is also a nice image that shows how those fields will be shown in Discord.
