### ISSUE TITLE
Migrate to new Discord Game SDK

### ISSUE THREAD

**Issue by abdonkov** [sll552/DiscordBee#36]
Hey, In another issue a guy asked about changing the "Playing" to "Listening" and you said that it is not possible because DiscordRPC wouldn't allow it.

However, the [DiscordRPC](https://discordapp.com/developers/docs/rich-presence/how-to#updating-presence-update-presence-payload-fields) is now deprecated in favour of the [Discord Game SDK](https://discordapp.com/developers/docs/game-sdk/sdk-starter-guide).
Now they haven't said anything about a future update to discord that may render DiscordRPC obsolete, but if you have time it is good for future proofing.
I see you have migrated to using discord-rpc-csharp which is reimplementation of the discord-rpc in C#, but this won't help if they decide to remove the old API needed for the discord rpc to work.

So could you consider switching to the new Discord Game SDK?
This can also help with the ["Listening to"](https://discordapp.com/developers/docs/game-sdk/activities#data-models-activitytype-enum) request...

**Comment by sll552** [comment]
As far as I know the Game SDK did not add any features regarding Rich Presence. It is just a new way to integrate Discord in your games. I am pretty sure it internally uses the same API for the Presence part as the old Discord-RPC lib did.
Because it did not add any relevant features for this project I decided to switch to discord-rpc-sharp instead.
Anyway, as soon as Discord decides to add a feature that adds something to this project (like the "listening" thing) I will consider switching to the SDK. Same of course if they decide to shutdown the current Rich Presence API.
Also the Game SDK seems to not be open source what I think is a step down from DiscordRPC.

**Comment by abdonkov** [comment]
It looks like the "listening" thing is supported [here](https://discordapp.com/developers/docs/game-sdk/activities#data-models-activitytype-enum) but the documentation for this SDK is really scarce and there isn't much info how to use it :)

**Comment by sll552** [comment]
> ActivityType is strictly for the purpose of handling events that you receive from Discord; though the SDK/our API will not reject a payload with an ActivityType sent, it will be discarded and will not change anything in the client.

So its there for you to parse but you cant set it unfortunately

**Comment by abdonkov** [comment]
Yeah so their API is just shit. Nice. No point in updating then.
