### ISSUE TITLE
The ability to change elapsed to "[CurrentTime] - [EndTime]"

### ISSUE THREAD

**Issue by AKASGaming** [sll552/DiscordBee#44]
If it's possible. could you add the ability to make it say something like:

**1:23 - 2:30**

The first time being the Current time, and the second time being the End time

**Comment by sll552** [comment]
The problem is that I cannot change the "elapsed" portion. This is something that discord does automatically and it is designed for games so basically this is intended as a round timer for games. 
It would be possible to create a field for the current playtime (if its not already available, I didn't check) but you would need to sacrifice one of the changeable fields (the ones you can edit in the settings)

**Comment by Rings4** [comment]
Foobar2000 and Winamp both have Discord Rich Presence apps that let you choose to either show the [TimeRemaining] or [TimeElapsed]. I feel that this would be a welcome compromise for now. I would rather display how close to the end of a song I am than my current progress, as others will have no frame of reference of my progress if they just see the current time (implying people actually care about my rich presence... heh).

**Comment by sll552** [comment]
This would be possible of course

**Comment by pazuzu156** [comment]
Been working on something like that (check box to show time remaining instead of elapsed) I can submit a PR tomorrow and have you review it

**Comment by pazuzu156** [comment]
I finished up working on my changes a little faster than I thought I would, and sent a pull request. Works fine on my end, we'll see how well it works for you
