### ISSUE TITLE
Not compatible with Better Discord?

### ISSUE THREAD

**Issue by plskillmeirl21** [sll552/DiscordBee#9]
It was perfectly working fine but after I install Better Discord it doesn't get detected by Discord anymore.

**Comment by sll552** [comment]
Do other RichPresence Apps work (e.g. Games like Fortnite, Divinity Original Sin 2, etc. )? 

Which Version of the Plugin are you using? 

I generally only support vanilla Discord because thats whats supported by the RichPresence Library. I might switch to a pure C# implementation in the future to get rid of the native dll but no timeframe on that.

**Comment by ohlookitsderpy** [comment]
Why are you using BetterDiscord in the first place? It's against Discord TOS and can get you banned.

**Comment by JustinADavidson** [comment]
Actually you won't get banned for using BetterDiscord they do say they don't want you to use it but they don't care if you do use it

**Comment by ohlookitsderpy** [comment]
That's what they used to say

**Comment by JustinADavidson** [comment]
It's what they still say because if they did ban users for using it I would be banned by now since I've used it for years

**Comment by ohlookitsderpy** [comment]
They don't actively hunt for users of it. They could do, but they don't. It's still an unnecessary risk which causes many security issues however, and shouldn't be encouraged so users don't go complaining around GitHub that they lost their Discord account and can't get it back.

I see no reason to continue an argument about whether to use client mods or not, especially on an issue I thought was long abandoned so I'm unsubscribing from this thread.

**Comment by JustinADavidson** [comment]
there is no risk involved with it all my friends use it there is 0 risk to using BetterDiscord unless you use banned plugins like Message Loggers as long as you stay clear from those Discord won't do anything

**Comment by sll552** [comment]
To get the curve back to this issue 😉 :

It is still open because the information I asked for was not provided. I don't really care if someone uses BetterDiscord or some other mods but I will not test them.
Also if there is an easy fix for problems with said mods I am happy to provide that or merge a pull request with a fix. But I won't invest time in trying to reproduce or debugging such an issue.
Personally I am using vanilla Discord so every Info that is needed to fix such an incompatibility has to be provided by the person who encountered the issue.

**Comment by JustinADavidson** [comment]
I haven't had any issues with the plugin on BetterDiscord so not sure what problem he is having

**Comment by JustinADavidson** [comment]
It may not even be related to BetterDiscord something else could be causing it

**Comment by sll552** [comment]
As according to @JustinADavidson the plugin seems to work with BetterDiscord I am closing this now.

For everyone who thinks there is a problem with BetterDiscord and this pluign, please open a new issue.

**Comment by Prateekkota** [comment]
Hey are the plugins which have like 100k downloads safe ?
Can I get banned from using those?

**Comment by Prateekkota** [comment]
I really want to know please :(
